### ISSUE TITLE
Image attachments in customizer

### ISSUE THREAD

**Issue by mandava** [fastlinemedia/customizer-export-import#1]
This is a neat plugin that does the job right. Image files are downloaded and imported properly, but they are not showing up in the customizer controls. However everything is fine with get_theme_mods and settings are perfect in front-end. 

![bg image](https://cloud.githubusercontent.com/assets/125006/5561644/f5959900-8db2-11e4-98ef-804753653797.PNG)

**Comment by fastlinemedia** [comment]
Hi Bharath, 

I’m glad you like the plugin! Can you let me know what theme you are having this issue with? Also, can you send me a copy of your export file? 

Thanks,
Justin
