### ISSUE TITLE
Snippet For Theme Developer

### ISSUE THREAD

**Issue by agusmu** [fastlinemedia/customizer-export-import#2]
Hi, it is not an issue, but a question because I can't find any answer.

So, on WPTavern article, I saw this image, 

![Export Import Install Message](http://i1.wp.com/wptavern.com/wp-content/uploads/2014/12/export-import-message.jpg)

> Theme authors can also add support for the plugin in order to avoid having to spin up their own export/import functionality, as Busa is doing with his current theme. The Export/Import panel in the customizer will prompt the user to install the plugin if he hasn’t already. “Additionally, theme authors could potentially offer any number of presets for their themes that users could import by leveraging this plugin,” Busa said.

Is there any code snippet that we can use to use this?

**Comment by fastlinemedia** [comment]
Thanks for asking! Are you familiar with creating and using custom controls? If so, I can send over some code for that. Let me know.

Justin

**Comment by agusmu** [comment]
Yes, I am.

**Comment by fastlinemedia** [comment]
Here's a gist of a custom control class that you can use. Let me know if you have any questions. 

https://gist.github.com/fastlinemedia/18b2b85686ee8aa37540

**Comment by agusmu** [comment]
Thanks a lot, I will give it a try...
