### ISSUE TITLE
Embedding in theme

### ISSUE THREAD

**Issue by hiro288** [fastlinemedia/customizer-export-import#7]
Hi,
Can i include it directly as a library in a theme?

**Comment by fastlinemedia** [comment]
I haven't tried doing that before but it might work out of the box. If not, you can use tgm plugin activation to include it in your theme... http://tgmpluginactivation.com/

**Comment by hiro288** [comment]
It worked! i just changed the constants.

`define( 'CEI_PLUGIN_DIR', wp_normalize_path( dirname( __FILE__ ) . '/') );`
`define( 'CEI_PLUGIN_URL', get_stylesheet_directory_uri() . '/options/cei' );`

**Comment by fastlinemedia** [comment]
I'm glad to hear that worked!
